### ISSUE TITLE
Footer is not sticked to bottom

### ISSUE THREAD

**Issue by Mysterious-Dev** [QuiltMC/developer-wiki#28] opened 2022-07-07 19:04 UTC
### Issue description

On large screens, the footer is not stuck to the bottom of the page (and this on all pages).

(2560x1440)
![image](https://user-images.githubusercontent.com/40738104/177852007-6583e38d-a444-47e1-8606-6b1c0369d1a2.png)

Web Browser : Firefox
Operating System : Windows 11

**Comment by gdude2002** [comment] 2022-07-25 19:31
Just to note that this is caused by the site's CSS, which the wiki uses. Relevant issue is here: https://github.com/QuiltMC/quiltmc.org/issues/53

**Comment by gdude2002** [comment] 2022-07-28 09:18
This should be fixed as of https://github.com/QuiltMC/quiltmc.org/commit/a2c288efaa8cecac0408e8914490d52659d2ac8f - which will be deployed in about ten minutes.

**Closed by gdude2002** 2022-07-28 09:18 UTC
Labels: bug
