### ISSUE TITLE
Footer icons are broken with Safari

### ISSUE THREAD

**Issue by tempest15** [QuiltMC/developer-wiki#1] opened 2022-06-10 00:36 UTC
The issue is present with Safari on desktop and mobile. When testing with Chrome on desktop, the issue was not present. The issue is also not present on the base website. Screenshots are below.

<img width="1552" alt="Screen Shot 2022-06-09 at 8 34 21 PM" src="https://user-images.githubusercontent.com/66021850/172967161-35d6e192-3a9a-4f99-b798-d7a055c76093.png">

![IMG_2413](https://user-images.githubusercontent.com/66021850/172967208-94fec3a3-9170-4f48-8a0b-b247834e22e7.PNG)

(first issue 🎉 )

**Comment by Mysterious-Dev** [comment] 2022-06-26 07:35
Do you see the icons on this page?

https://quiltmc.org/

**Comment by Southpaw1496** [comment] 2022-06-26 08:06
I can reproduce this. Some points to keep in mind:
- Safari does support SVG rendering.
- I have tested it on Safari and Firefox, and Firefox works, but Safari doesn't, so this is a browser-specific  issue.
- [The footer on quiltmc.org](https://github.com/QuiltMC/quiltmc.org/blob/stable/src/_includes/footer.liquid), which I believe uses the same icons, works fine.

**Comment by Mysterious-Dev** [comment] 2022-07-24 18:08
With recent changes, can you check if the bug persists ?

**Comment by Southpaw1496** [comment] 2022-07-24 18:09
It does not, most likely fixed by https://github.com/QuiltMC/developer-wiki/commit/a26b3fc1f0fad583e5c3106f0a4d9f9b39e61b3a

**Comment by gdude2002** [comment] 2022-07-25 18:04
This shouldn't be an issue regardless because the icons were being used entirely incorrectly previously, and are now set up to match the site. Feel free to let us know if this isn't the case, though.

**Closed by gdude2002** 2022-07-25 18:04 UTC
Labels: bug, good first issue, Infrastructure
